# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs: 
  - job: job1
    steps:
    - bash: echo job1 build
  - job: job2
    steps:
    - bash: echo job2 build
- stage: devDeploy
  dependsOn: build
  jobs: 
  - job: devDeployjob1
    steps:
    - bash: echo devDeployjob1 build
    - bash: $(env_var)
- stage: QADeploy
  dependsOn: build
  jobs: 
  - job: QADeployjob1
    steps:
    - bash: echo QADeployjob1 build
- stage: ProdDeploy
  dependsOn: QADeploy
  jobs: 
  - job: ProdDeployjob1
    steps:
    - bash: echo ProdDeployjob1 build



