
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: build
  jobs:
  - job: Buildjob1
    steps:
    - bash: echo Build Test!

- stage: Dev build
  jobs:
  -  deployment: 
     environment: Dev
     strategy: 
      runOnce:
        deploy:
          steps:
          -  script: echo deploy to  dev $(environment)
          
- stage: QA build
  jobs:
  -  deployment: 
     environment: QA
     strategy: 
      runOnce:
        deploy:
          steps:
          -  script: echo deploy to qa

